# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

# build cache to preserve files/folders between builds
cache:
  - node_modules                    # local npm modules
  
install:
  - cmd: npm ci

build_script:
  - cmd: npm run build


# to run your custom scripts instead of automatic tests
test_script:
  - cmd: npm run test

artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.js, **\*.html, **\*.htm, **\*.css'

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: UVaEtrl0de6B2M1uiG6kwJ/0yg5+/QBswMsc6ywG/8nyiJtobOz5K/gmR2/Gu4yFbVtH7oxqUXtyFeKx9ppDLGbO5Zvi8F2JuRjZkDybf1BeBvsAYPe0+qEuhAF/pq8H
    artifact: /.*\.*/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
