version: 1.0.{build}
install:
- cmd: npm ci
build_script:
- cmd: npm run build
test_script:
- cmd: npm run test
deploy_script:
  - ps: |
      git config --global user.email "fazendadn@gmail.com"
      git config --global user.name "Dmytro Ostretsov"
      git clone -b gh-pages https://$env:GITHUB_AUTH_TOKEN@github.com/dmytro-ost/dmytro-ost.git deploy
      cd deploy
      rm -rf *  # Remove old content
      cp -r ../dist/* .  # Copy only the built site
      git add .
      git commit -m "Deploy to GitHub Pages [skip ci]"
      git push origin gh-pages

# Cache dependencies for faster builds
cache:
  - node_modules

# Environment variables (GitHub auth token)
environment:
  GITHUB_AUTH_TOKEN:
    secure: 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

# Skip builds for commits with [skip ci]
skip_commits:
  message: /.*\[skip ci\].*/
